rule("debug")
    on_load(function (target)
        target:set("symbols", "debug")
        target:set("optimize", "none")
        target:add("defines", "DEBUG", "_DEBUG")
    end)
rule_end()
rule("release")
    on_load(function (target)
        target:add("defines", "NDEBUG")
        target:set("optimize", "fastest")
        target:set("strip", "all")
        target:set("policy", "build.optimization.lto", true)
    end)
rule_end()
rule("minsizerel")
    on_load(function (target)
        target:add("defines", "NDEBUG")
        target:set("optimize", "smallest")
        target:set("strip", "all")
        target:set("policy", "build.optimization.lto", true)
    end)
rule_end()
rule("releasedbg")
    on_load(function (target)
        target:set("optimize", "fastest")
        target:set("symbols", "debug")
        target:set("policy", "build.optimization.lto", true)
    end)
rule_end()
