includes("option.lua")
local debug_strip = get_config("debug_strip")
if debug_strip == "no" then -- 不剥离符号
    debug_strip = nil
end
local enable_lto = get_config("enable_lto")

rule("debug")
    on_load(function (target)
        target:set("symbols", "debug")
        target:set("optimize", "none")
        target:add("defines", "DEBUG", "_DEBUG")
        target:set("strip", debug_strip)
    end)
rule_end()
rule("release")
    on_load(function (target)
        target:add("defines", "NDEBUG")
        target:set("optimize", "fastest")
        target:set("strip", "all")
        target:set("policy", "build.optimization.lto", enable_lto)
    end)
rule_end()
rule("minsizerel")
    on_load(function (target)
        target:add("defines", "NDEBUG")
        target:set("optimize", "smallest")
        target:set("strip", "all")
        target:set("policy", "build.optimization.lto", enable_lto)
    end)
rule_end()
rule("releasedbg")
    on_load(function (target)
        target:set("optimize", "fastest")
        target:set("symbols", "debug")
        target:set("policy", "build.optimization.lto", enable_lto)
        target:set("strip", debug_strip)
    end)
rule_end()

-- 受支持的规则表
support_rules_table = {"debug", "release", "minsizerel", "releasedbg"}
